name: Update KNMI Weather Data

on:
  schedule:
    - cron: '0 6 * * *'  # Elke dag om 06:00 UTC (08:00 NL-tijd)
  workflow_dispatch:     # Manueel triggeren ook mogelijk

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openpyxl

      - name: Run update script
        run: python path/to/your_script.py
