name: Daily Energy Price Update

on:
  schedule:
    - cron: '15 12 * * *'  # every day at 13:15 CET
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python Realized_energy_prices.py

    - name: Commit and push updated file
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add realized_energy_prices.xlsx
        git commit -m "📈 Auto-update energy prices"
        git push
