name: Daily Energy Price Update

on:
  schedule:
    - cron: '15 12 * * *'  # Every day at 13:15 CET (12:15 UTC)
  workflow_dispatch:        # Also allows manual run

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: python realized_energy_prices.py

    - name: Commit and push updated file
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add Realized_energy_prices.xlsx
        git commit -m "📈 Auto-update energy prices"
        git push
